var b0 = {
	TestID: "1",
	name:"Blue Sky",
	type:"Resturant",
	city:"Tal-Aviv",
	address:"Aliezer Per 10",
	phone:"0505505550",
	email:"FriendlyReviewsTeam@gmail.com",
	avgOverallRat:"4",
	avgPriceRat:"4",
	avgQualityRat:"4",
	avgParkingRat:"4",
	LastUpdate:"1/1/14",
	picture:"c:\myPic.jpg",
	geoLocCoords:{type:"Point",
				   coordinates: [32.087501,34.770141]},
	ratingFromReviewsOne: 0,
	ratingFromReviewsTwo: 0,
	ratingFromReviewsThree: 0,
	ratingFromReviewsFour: 0,
	ratingFromReviewsFive: 0,
	ratingFromReviewsTotal: 0,

	qualityRatingFromReviewsTotal: 0,
	parkingRatingFromReviewsTotal: 0,
	priceRatingFromReviewsTotal: 0

},	
b1 = {
	TestID: "2",
	name:"Donia",
	type:"Resturant",
	city:"Jerusalem",
	address:"Shlomzion hamalca 1",
	phone:"0505505550",
	email:"FriendlyReviewsTeam@gmail.com",
	avgOverallRat:"4",
	avgPriceRat:"4",
	avgQualityRat:"4",
	avgParkingRat:"4",
	LastUpdate:"1/1/14",
	picture:"c:\myPic.jpg",
	geoLocCoords:{type:"Point",
				   coordinates: [31.780605,35.221632]},
	ratingFromReviewsOne: 0,
	ratingFromReviewsTwo: 0,
	ratingFromReviewsThree: 0,
	ratingFromReviewsFour: 0,
	ratingFromReviewsFive: 0,
	ratingFromReviewsTotal: 0,

	qualityRatingFromReviewsTotal: 0,
	parkingRatingFromReviewsTotal: 0,
	priceRatingFromReviewsTotal: 0
},
	
b2 = {
	TestID: "3",
	name:"El-Gauch",
	type:"Resturant",
	city:"Rishon-le-zion",
	address:"hamacabim 40",
	phone:"0505505550",
	email:"FriendlyReviewsTeam@gmail.com",
	avgOverallRat:"4",
	avgPriceRat:"4",
	avgQualityRat:"4",
	avgParkingRat:"4",
	LastUpdate:"1/1/14",
	picture:"c:\myPic.jpg",
	geoLocCoords:{type:"Point",
				   coordinates: [31.980487,34.809258]},
	ratingFromReviewsOne: 0,
	ratingFromReviewsTwo: 0,
	ratingFromReviewsThree: 0,
	ratingFromReviewsFour: 0,
	ratingFromReviewsFive: 0,
	ratingFromReviewsTotal: 0,

	qualityRatingFromReviewsTotal: 0,
	parkingRatingFromReviewsTotal: 0,
	priceRatingFromReviewsTotal: 0
},
	
b3 = {
	TestID: "4",
	name:"paka-paka",
	type:"Bar",
	city:"Rehovot",
	address:"herzel 207",
	phone:"0505505550",
	email:"FriendlyReviewsTeam@gmail.com",
	avgOverallRat:"4",
	avgPriceRat:"4",
	avgQualityRat:"4",
	avgParkingRat:"4",
	LastUpdate:"1/1/14",
	picture:"c:\myPic.jpg",
	geoLocCoords:{type: "Point",
				   coordinates: [31.902481,34.808722]},
	ratingFromReviewsOne: 0,
	ratingFromReviewsTwo: 0,
	ratingFromReviewsThree: 0,
	ratingFromReviewsFour: 0,
	ratingFromReviewsFive: 0,
	ratingFromReviewsTotal: 0,

	qualityRatingFromReviewsTotal: 0,
	parkingRatingFromReviewsTotal: 0,
	priceRatingFromReviewsTotal: 0
},
	
b4 = {
	TestID: "5",
	name:"Caeser",
	type:"Bar",
	city:"Gdera",
	address:"habiluim 5",
	phone:"0505505550",
	email:"FriendlyReviewsTeam@gmail.com",
	avgOverallRat:"4",
	avgPriceRat:"4",
	avgQualityRat:"4",
	avgParkingRat:"4",
	LastUpdate:"1/1/14",
	picture:"c:\myPic.jpg",
	geoLocCoords: { type:"Point",
				    coordinates: [31.815766,34.773102]},
	ratingFromReviewsOne: 0,
	ratingFromReviewsTwo: 0,
	ratingFromReviewsThree: 0,
	ratingFromReviewsFour: 0,
	ratingFromReviewsFive: 0,
	ratingFromReviewsTotal: 0,

	qualityRatingFromReviewsTotal: 0,
	parkingRatingFromReviewsTotal: 0,
	priceRatingFromReviewsTotal: 0
},
	
b5 = {
	TestID: "6",
	name: "Albert",
	type: "Resturant",
	city: "Jafa",
	address: "Bat-ami 5",
	phone:"0505505550",
	email:"FriendlyReviewsTeam@gmail.com",
	avgOverallRat: "4",
	avgPriceRat: "4",
	avgQualityRat: "4",
	avgParkingRat: "4",
	LastUpdate: "1/1/14",
	picture: "c:\myPic.jpg",
	geoLocCoords: { type: "Point",
				    coordinates: [32.056718,34.760098]},
	ratingFromReviewsOne: 0,
	ratingFromReviewsTwo: 0,
	ratingFromReviewsThree: 0,
	ratingFromReviewsFour: 0,
	ratingFromReviewsFive: 0,
	ratingFromReviewsTotal: 0,

	qualityRatingFromReviewsTotal: 0,
	parkingRatingFromReviewsTotal: 0,
	priceRatingFromReviewsTotal: 0

},
	
b6 = {
	TestID: "7",
	name: "Metoka",
	type: "Restaurant",
	city: "Holon",
	address: "Habanay 5",
	phone:"0505505550",
	email:"FriendlyReviewsTeam@gmail.com",
	avgOverallRat: "4",
	avgPriceRat: "4",
	avgQualityRat: "4",
	avgParkingRat: "4",
	LastUpdate: "1/1/14",
	picture: "c:\myPic.jpg",
	geoLocCoords: { type:"Point",
				    coordinates: [32.015863,34.804623]},
	ratingFromReviewsOne: 0,
	ratingFromReviewsTwo: 0,
	ratingFromReviewsThree: 0,
	ratingFromReviewsFour: 0,
	ratingFromReviewsFive: 0,
	ratingFromReviewsTotal: 0,

	qualityRatingFromReviewsTotal: 0,
	parkingRatingFromReviewsTotal: 0,
	priceRatingFromReviewsTotal: 0
},
	
b7 = {
	TestID: "8",
	name: "YesPlanet",
	type: "Movie",
	city: "Rishon-le-zion",
	address: "Hamea veesrim 4",
	phone:"0505505550",
	email:"FriendlyReviewsTeam@gmail.com",
	avgOverallRat: "4",
	avgPriceRat: "4",
	avgQualityRat: "4",
	avgParkingRat: "4",
	LastUpdate: "1/1/14",
	picture: "c:\myPic.jpg",
	geoLocCoords:{type: "Point" ,
				   coordinates: [31.98289,34.747868]},
	ratingFromReviewsOne: 0,
	ratingFromReviewsTwo: 0,
	ratingFromReviewsThree: 0,
	ratingFromReviewsFour: 0,
	ratingFromReviewsFive: 0,
	ratingFromReviewsTotal: 0,

	qualityRatingFromReviewsTotal: 0,
	parkingRatingFromReviewsTotal: 0,
	priceRatingFromReviewsTotal: 0
},
	
b8 = {
	TestID: "9",
	name:"Rav-Hen",
	type:"Movie",
	city:"Modiin",
	address:"Lev-haeer 1",
	phone:"0505505550",
	email:"FriendlyReviewsTeam@gmail.com",
	avgOverallRat:"4",
	avgPriceRat:"4",
	avgQualityRat:"4",
	avgParkingRat:"4",
	LastUpdate:"1/1/14",
	picture:"c:\myPic.jpg",
	geoLocCoords: {type: "Point" ,
				   coordinates: [31.899858,35.00772]},
	ratingFromReviewsOne: 0,
	ratingFromReviewsTwo: 0,
	ratingFromReviewsThree: 0,
	ratingFromReviewsFour: 0,
	ratingFromReviewsFive: 0,
	ratingFromReviewsTotal: 0,

	qualityRatingFromReviewsTotal: 0,
	parkingRatingFromReviewsTotal: 0,
	priceRatingFromReviewsTotal: 0
};

var BusinessesArr = [];
BusinessesArr[0] = b0;
BusinessesArr[1] = b1;
BusinessesArr[2] = b2;
BusinessesArr[3] = b3;
BusinessesArr[4] = b4;
BusinessesArr[5] = b5;
BusinessesArr[6] = b6;
BusinessesArr[7] = b7;
BusinessesArr[8] = b8;


exports.BusinessesArr = BusinessesArr;
